spring:
  application:
    name: online_exam

  datasource:
    url: jdbc:mysql://localhost:3306/online_exam?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      # password: yourpassword   # bỏ comment nếu Redis có đặt password
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhliem27diem@gmail.com
    password: "cmml niwl jbho xwro"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8081

jwt:
  secret: mySecretKeyForJwtTokenMustBeLongEnough123456
  access-expire: 3600000
  refresh-expire: 604800000

app:
  mail:
    from-name: ExamPortal
  refresh-token:
    ttl-seconds: 604800   # 7 ngày
  activity-log:
    retention-days: 30        # đổi số này tùy ý
    cleanup-cron: "0 5 3 * * *"
gemini:
  api:
    key: AIzaSyBujx9y3FsuxZ_WeTjK8Sa7l8rZXLtq2SA
  model: gemini-2.5-flash