package com.example.online_exam.activitylog.entity;

public enum ActivityLogAction {
    // Auth
    LOGIN, LOGOUT, REGISTER, FORGOT_PASSWORD, RESET_PASSWORD,

    // User management (admin)
    CREATE_USER, UPDATE_USER, DELETE_USER,
    RESET_USER_PASSWORD, TOGGLE_USER_STATUS,
    // Profile (self)
    CHANGE_PASSWORD, UPDATE_PROFILE, UPDATE_AVATAR,

    // Course
    CREATE_COURSE, UPDATE_COURSE, DELETE_COURSE,
    ADD_STUDENT, REMOVE_STUDENT,

    // Question
    CREATE_QUESTION, UPDATE_QUESTION, DELETE_QUESTION,

    // Exam
    CREATE_EXAM, UPDATE_EXAM, DELETE_EXAM,
    PUBLISH_EXAM, CLOSE_EXAM,

    // Attempt
    START_EXAM, SUBMIT_ATTEMPT, GRADE_ATTEMPT, RESET_ATTEMPT,

    // Tag
    CREATE_TAG, UPDATE_TAG, DELETE_TAG,

    // Discussion
    CREATE_POST, UPDATE_POST, DELETE_POST,
    CREATE_REPLY, UPDATE_REPLY, DELETE_REPLY,
    MARK_BEST_ANSWER, REPORT_CONTENT,

    // Moderation (admin)
    DISMISS_REPORT, DELETE_CONTENT,
    WARN_USER, MUTE_USER, BAN_USER, UNBAN_USER
}
